//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Victus.VictusWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="VictusWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class VictusWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BuscarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarUsuarioTodoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarUltimoRegistroOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarDatosClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarUltimoRegistroHarrisOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarRegistroHarrisOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarRegistroHarrisOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarDietaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerUltimaDietaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerDietaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarRelacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerCatalogoAlimentosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerDietaCompletaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarMedidasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerUltimaMedidaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerMedidaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerMedicionCompletaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public VictusWebService() {
            this.Url = "http://www.victusws.somee.com/VictusWebService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BuscarUsuarioCompletedEventHandler BuscarUsuarioCompleted;
        
        /// <remarks/>
        public event BuscarUsuarioTodoCompletedEventHandler BuscarUsuarioTodoCompleted;
        
        /// <remarks/>
        public event CrearUsuarioCompletedEventHandler CrearUsuarioCompleted;
        
        /// <remarks/>
        public event BuscarClienteCompletedEventHandler BuscarClienteCompleted;
        
        /// <remarks/>
        public event BuscarUltimoRegistroCompletedEventHandler BuscarUltimoRegistroCompleted;
        
        /// <remarks/>
        public event AgregarDatosClienteCompletedEventHandler AgregarDatosClienteCompleted;
        
        /// <remarks/>
        public event BuscarUltimoRegistroHarrisCompletedEventHandler BuscarUltimoRegistroHarrisCompleted;
        
        /// <remarks/>
        public event BuscarRegistroHarrisCompletedEventHandler BuscarRegistroHarrisCompleted;
        
        /// <remarks/>
        public event AgregarRegistroHarrisCompletedEventHandler AgregarRegistroHarrisCompleted;
        
        /// <remarks/>
        public event AgregarDietaCompletedEventHandler AgregarDietaCompleted;
        
        /// <remarks/>
        public event ObtenerUltimaDietaCompletedEventHandler ObtenerUltimaDietaCompleted;
        
        /// <remarks/>
        public event ObtenerDietaCompletedEventHandler ObtenerDietaCompleted;
        
        /// <remarks/>
        public event AgregarRelacionCompletedEventHandler AgregarRelacionCompleted;
        
        /// <remarks/>
        public event ObtenerCatalogoAlimentosCompletedEventHandler ObtenerCatalogoAlimentosCompleted;
        
        /// <remarks/>
        public event ObtenerDietaCompletaCompletedEventHandler ObtenerDietaCompletaCompleted;
        
        /// <remarks/>
        public event AgregarMedidasCompletedEventHandler AgregarMedidasCompleted;
        
        /// <remarks/>
        public event ObtenerUltimaMedidaCompletedEventHandler ObtenerUltimaMedidaCompleted;
        
        /// <remarks/>
        public event ObtenerMedidaCompletedEventHandler ObtenerMedidaCompleted;
        
        /// <remarks/>
        public event ObtenerMedicionCompletaCompletedEventHandler ObtenerMedicionCompletaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable BuscarUsuario(string Correo) {
            object[] results = this.Invoke("BuscarUsuario", new object[] {
                        Correo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarUsuarioAsync(string Correo) {
            this.BuscarUsuarioAsync(Correo, null);
        }
        
        /// <remarks/>
        public void BuscarUsuarioAsync(string Correo, object userState) {
            if ((this.BuscarUsuarioOperationCompleted == null)) {
                this.BuscarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarUsuarioOperationCompleted);
            }
            this.InvokeAsync("BuscarUsuario", new object[] {
                        Correo}, this.BuscarUsuarioOperationCompleted, userState);
        }
        
        private void OnBuscarUsuarioOperationCompleted(object arg) {
            if ((this.BuscarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarUsuarioCompleted(this, new BuscarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarUsuarioTodo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable BuscarUsuarioTodo(string Correo) {
            object[] results = this.Invoke("BuscarUsuarioTodo", new object[] {
                        Correo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarUsuarioTodoAsync(string Correo) {
            this.BuscarUsuarioTodoAsync(Correo, null);
        }
        
        /// <remarks/>
        public void BuscarUsuarioTodoAsync(string Correo, object userState) {
            if ((this.BuscarUsuarioTodoOperationCompleted == null)) {
                this.BuscarUsuarioTodoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarUsuarioTodoOperationCompleted);
            }
            this.InvokeAsync("BuscarUsuarioTodo", new object[] {
                        Correo}, this.BuscarUsuarioTodoOperationCompleted, userState);
        }
        
        private void OnBuscarUsuarioTodoOperationCompleted(object arg) {
            if ((this.BuscarUsuarioTodoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarUsuarioTodoCompleted(this, new BuscarUsuarioTodoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrearUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CrearUsuario(string correo, int cedula, string nombre, string apellido1, string apellido2, bool genero, string contraseña) {
            object[] results = this.Invoke("CrearUsuario", new object[] {
                        correo,
                        cedula,
                        nombre,
                        apellido1,
                        apellido2,
                        genero,
                        contraseña});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CrearUsuarioAsync(string correo, int cedula, string nombre, string apellido1, string apellido2, bool genero, string contraseña) {
            this.CrearUsuarioAsync(correo, cedula, nombre, apellido1, apellido2, genero, contraseña, null);
        }
        
        /// <remarks/>
        public void CrearUsuarioAsync(string correo, int cedula, string nombre, string apellido1, string apellido2, bool genero, string contraseña, object userState) {
            if ((this.CrearUsuarioOperationCompleted == null)) {
                this.CrearUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearUsuarioOperationCompleted);
            }
            this.InvokeAsync("CrearUsuario", new object[] {
                        correo,
                        cedula,
                        nombre,
                        apellido1,
                        apellido2,
                        genero,
                        contraseña}, this.CrearUsuarioOperationCompleted, userState);
        }
        
        private void OnCrearUsuarioOperationCompleted(object arg) {
            if ((this.CrearUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearUsuarioCompleted(this, new CrearUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable BuscarCliente(string correo, System.DateTime fecha) {
            object[] results = this.Invoke("BuscarCliente", new object[] {
                        correo,
                        fecha});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarClienteAsync(string correo, System.DateTime fecha) {
            this.BuscarClienteAsync(correo, fecha, null);
        }
        
        /// <remarks/>
        public void BuscarClienteAsync(string correo, System.DateTime fecha, object userState) {
            if ((this.BuscarClienteOperationCompleted == null)) {
                this.BuscarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarClienteOperationCompleted);
            }
            this.InvokeAsync("BuscarCliente", new object[] {
                        correo,
                        fecha}, this.BuscarClienteOperationCompleted, userState);
        }
        
        private void OnBuscarClienteOperationCompleted(object arg) {
            if ((this.BuscarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarClienteCompleted(this, new BuscarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarUltimoRegistro", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable BuscarUltimoRegistro(string correo) {
            object[] results = this.Invoke("BuscarUltimoRegistro", new object[] {
                        correo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarUltimoRegistroAsync(string correo) {
            this.BuscarUltimoRegistroAsync(correo, null);
        }
        
        /// <remarks/>
        public void BuscarUltimoRegistroAsync(string correo, object userState) {
            if ((this.BuscarUltimoRegistroOperationCompleted == null)) {
                this.BuscarUltimoRegistroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarUltimoRegistroOperationCompleted);
            }
            this.InvokeAsync("BuscarUltimoRegistro", new object[] {
                        correo}, this.BuscarUltimoRegistroOperationCompleted, userState);
        }
        
        private void OnBuscarUltimoRegistroOperationCompleted(object arg) {
            if ((this.BuscarUltimoRegistroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarUltimoRegistroCompleted(this, new BuscarUltimoRegistroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarDatosCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AgregarDatosCliente(string Correo, double Peso, int Altura, int Edad, double IMC, int Agua, System.DateTime Fecha) {
            object[] results = this.Invoke("AgregarDatosCliente", new object[] {
                        Correo,
                        Peso,
                        Altura,
                        Edad,
                        IMC,
                        Agua,
                        Fecha});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarDatosClienteAsync(string Correo, double Peso, int Altura, int Edad, double IMC, int Agua, System.DateTime Fecha) {
            this.AgregarDatosClienteAsync(Correo, Peso, Altura, Edad, IMC, Agua, Fecha, null);
        }
        
        /// <remarks/>
        public void AgregarDatosClienteAsync(string Correo, double Peso, int Altura, int Edad, double IMC, int Agua, System.DateTime Fecha, object userState) {
            if ((this.AgregarDatosClienteOperationCompleted == null)) {
                this.AgregarDatosClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarDatosClienteOperationCompleted);
            }
            this.InvokeAsync("AgregarDatosCliente", new object[] {
                        Correo,
                        Peso,
                        Altura,
                        Edad,
                        IMC,
                        Agua,
                        Fecha}, this.AgregarDatosClienteOperationCompleted, userState);
        }
        
        private void OnAgregarDatosClienteOperationCompleted(object arg) {
            if ((this.AgregarDatosClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarDatosClienteCompleted(this, new AgregarDatosClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarUltimoRegistroHarris", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable BuscarUltimoRegistroHarris(string correo) {
            object[] results = this.Invoke("BuscarUltimoRegistroHarris", new object[] {
                        correo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarUltimoRegistroHarrisAsync(string correo) {
            this.BuscarUltimoRegistroHarrisAsync(correo, null);
        }
        
        /// <remarks/>
        public void BuscarUltimoRegistroHarrisAsync(string correo, object userState) {
            if ((this.BuscarUltimoRegistroHarrisOperationCompleted == null)) {
                this.BuscarUltimoRegistroHarrisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarUltimoRegistroHarrisOperationCompleted);
            }
            this.InvokeAsync("BuscarUltimoRegistroHarris", new object[] {
                        correo}, this.BuscarUltimoRegistroHarrisOperationCompleted, userState);
        }
        
        private void OnBuscarUltimoRegistroHarrisOperationCompleted(object arg) {
            if ((this.BuscarUltimoRegistroHarrisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarUltimoRegistroHarrisCompleted(this, new BuscarUltimoRegistroHarrisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarRegistroHarris", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable BuscarRegistroHarris(string correo, System.DateTime fecha) {
            object[] results = this.Invoke("BuscarRegistroHarris", new object[] {
                        correo,
                        fecha});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarRegistroHarrisAsync(string correo, System.DateTime fecha) {
            this.BuscarRegistroHarrisAsync(correo, fecha, null);
        }
        
        /// <remarks/>
        public void BuscarRegistroHarrisAsync(string correo, System.DateTime fecha, object userState) {
            if ((this.BuscarRegistroHarrisOperationCompleted == null)) {
                this.BuscarRegistroHarrisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarRegistroHarrisOperationCompleted);
            }
            this.InvokeAsync("BuscarRegistroHarris", new object[] {
                        correo,
                        fecha}, this.BuscarRegistroHarrisOperationCompleted, userState);
        }
        
        private void OnBuscarRegistroHarrisOperationCompleted(object arg) {
            if ((this.BuscarRegistroHarrisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarRegistroHarrisCompleted(this, new BuscarRegistroHarrisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarRegistroHarris", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AgregarRegistroHarris(double FactorActividad, double TMB, double NivelCalorico, System.DateTime fecha, string correo) {
            object[] results = this.Invoke("AgregarRegistroHarris", new object[] {
                        FactorActividad,
                        TMB,
                        NivelCalorico,
                        fecha,
                        correo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarRegistroHarrisAsync(double FactorActividad, double TMB, double NivelCalorico, System.DateTime fecha, string correo) {
            this.AgregarRegistroHarrisAsync(FactorActividad, TMB, NivelCalorico, fecha, correo, null);
        }
        
        /// <remarks/>
        public void AgregarRegistroHarrisAsync(double FactorActividad, double TMB, double NivelCalorico, System.DateTime fecha, string correo, object userState) {
            if ((this.AgregarRegistroHarrisOperationCompleted == null)) {
                this.AgregarRegistroHarrisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarRegistroHarrisOperationCompleted);
            }
            this.InvokeAsync("AgregarRegistroHarris", new object[] {
                        FactorActividad,
                        TMB,
                        NivelCalorico,
                        fecha,
                        correo}, this.AgregarRegistroHarrisOperationCompleted, userState);
        }
        
        private void OnAgregarRegistroHarrisOperationCompleted(object arg) {
            if ((this.AgregarRegistroHarrisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarRegistroHarrisCompleted(this, new AgregarRegistroHarrisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarDieta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AgregarDieta(string CorreoCliente, System.DateTime FechaDieta, int CodigoHarris, string Objetivo) {
            object[] results = this.Invoke("AgregarDieta", new object[] {
                        CorreoCliente,
                        FechaDieta,
                        CodigoHarris,
                        Objetivo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarDietaAsync(string CorreoCliente, System.DateTime FechaDieta, int CodigoHarris, string Objetivo) {
            this.AgregarDietaAsync(CorreoCliente, FechaDieta, CodigoHarris, Objetivo, null);
        }
        
        /// <remarks/>
        public void AgregarDietaAsync(string CorreoCliente, System.DateTime FechaDieta, int CodigoHarris, string Objetivo, object userState) {
            if ((this.AgregarDietaOperationCompleted == null)) {
                this.AgregarDietaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarDietaOperationCompleted);
            }
            this.InvokeAsync("AgregarDieta", new object[] {
                        CorreoCliente,
                        FechaDieta,
                        CodigoHarris,
                        Objetivo}, this.AgregarDietaOperationCompleted, userState);
        }
        
        private void OnAgregarDietaOperationCompleted(object arg) {
            if ((this.AgregarDietaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarDietaCompleted(this, new AgregarDietaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerUltimaDieta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ObtenerUltimaDieta(string CorreoCliente) {
            object[] results = this.Invoke("ObtenerUltimaDieta", new object[] {
                        CorreoCliente});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerUltimaDietaAsync(string CorreoCliente) {
            this.ObtenerUltimaDietaAsync(CorreoCliente, null);
        }
        
        /// <remarks/>
        public void ObtenerUltimaDietaAsync(string CorreoCliente, object userState) {
            if ((this.ObtenerUltimaDietaOperationCompleted == null)) {
                this.ObtenerUltimaDietaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerUltimaDietaOperationCompleted);
            }
            this.InvokeAsync("ObtenerUltimaDieta", new object[] {
                        CorreoCliente}, this.ObtenerUltimaDietaOperationCompleted, userState);
        }
        
        private void OnObtenerUltimaDietaOperationCompleted(object arg) {
            if ((this.ObtenerUltimaDietaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerUltimaDietaCompleted(this, new ObtenerUltimaDietaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerDieta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ObtenerDieta(string CorreoCliente, System.DateTime FechaDieta) {
            object[] results = this.Invoke("ObtenerDieta", new object[] {
                        CorreoCliente,
                        FechaDieta});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerDietaAsync(string CorreoCliente, System.DateTime FechaDieta) {
            this.ObtenerDietaAsync(CorreoCliente, FechaDieta, null);
        }
        
        /// <remarks/>
        public void ObtenerDietaAsync(string CorreoCliente, System.DateTime FechaDieta, object userState) {
            if ((this.ObtenerDietaOperationCompleted == null)) {
                this.ObtenerDietaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerDietaOperationCompleted);
            }
            this.InvokeAsync("ObtenerDieta", new object[] {
                        CorreoCliente,
                        FechaDieta}, this.ObtenerDietaOperationCompleted, userState);
        }
        
        private void OnObtenerDietaOperationCompleted(object arg) {
            if ((this.ObtenerDietaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerDietaCompleted(this, new ObtenerDietaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarRelacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AgregarRelacion(int CodigoDieta, int CodigoAlimento) {
            object[] results = this.Invoke("AgregarRelacion", new object[] {
                        CodigoDieta,
                        CodigoAlimento});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarRelacionAsync(int CodigoDieta, int CodigoAlimento) {
            this.AgregarRelacionAsync(CodigoDieta, CodigoAlimento, null);
        }
        
        /// <remarks/>
        public void AgregarRelacionAsync(int CodigoDieta, int CodigoAlimento, object userState) {
            if ((this.AgregarRelacionOperationCompleted == null)) {
                this.AgregarRelacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarRelacionOperationCompleted);
            }
            this.InvokeAsync("AgregarRelacion", new object[] {
                        CodigoDieta,
                        CodigoAlimento}, this.AgregarRelacionOperationCompleted, userState);
        }
        
        private void OnAgregarRelacionOperationCompleted(object arg) {
            if ((this.AgregarRelacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarRelacionCompleted(this, new AgregarRelacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerCatalogoAlimentos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ObtenerCatalogoAlimentos() {
            object[] results = this.Invoke("ObtenerCatalogoAlimentos", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerCatalogoAlimentosAsync() {
            this.ObtenerCatalogoAlimentosAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerCatalogoAlimentosAsync(object userState) {
            if ((this.ObtenerCatalogoAlimentosOperationCompleted == null)) {
                this.ObtenerCatalogoAlimentosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerCatalogoAlimentosOperationCompleted);
            }
            this.InvokeAsync("ObtenerCatalogoAlimentos", new object[0], this.ObtenerCatalogoAlimentosOperationCompleted, userState);
        }
        
        private void OnObtenerCatalogoAlimentosOperationCompleted(object arg) {
            if ((this.ObtenerCatalogoAlimentosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerCatalogoAlimentosCompleted(this, new ObtenerCatalogoAlimentosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerDietaCompleta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ObtenerDietaCompleta(string CorreoCliente, int CodigoDieta) {
            object[] results = this.Invoke("ObtenerDietaCompleta", new object[] {
                        CorreoCliente,
                        CodigoDieta});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerDietaCompletaAsync(string CorreoCliente, int CodigoDieta) {
            this.ObtenerDietaCompletaAsync(CorreoCliente, CodigoDieta, null);
        }
        
        /// <remarks/>
        public void ObtenerDietaCompletaAsync(string CorreoCliente, int CodigoDieta, object userState) {
            if ((this.ObtenerDietaCompletaOperationCompleted == null)) {
                this.ObtenerDietaCompletaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerDietaCompletaOperationCompleted);
            }
            this.InvokeAsync("ObtenerDietaCompleta", new object[] {
                        CorreoCliente,
                        CodigoDieta}, this.ObtenerDietaCompletaOperationCompleted, userState);
        }
        
        private void OnObtenerDietaCompletaOperationCompleted(object arg) {
            if ((this.ObtenerDietaCompletaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerDietaCompletaCompleted(this, new ObtenerDietaCompletaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarMedidas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AgregarMedidas(System.DateTime FechaMedida, string CorreoCliente, double BicepIzquierdo, double BicepDerecho, double Abdomen, double CuadricepIzquierdo, double CuadricepDerecho, double PantorrillaIzquierda, double PantorrillaDerecha) {
            object[] results = this.Invoke("AgregarMedidas", new object[] {
                        FechaMedida,
                        CorreoCliente,
                        BicepIzquierdo,
                        BicepDerecho,
                        Abdomen,
                        CuadricepIzquierdo,
                        CuadricepDerecho,
                        PantorrillaIzquierda,
                        PantorrillaDerecha});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarMedidasAsync(System.DateTime FechaMedida, string CorreoCliente, double BicepIzquierdo, double BicepDerecho, double Abdomen, double CuadricepIzquierdo, double CuadricepDerecho, double PantorrillaIzquierda, double PantorrillaDerecha) {
            this.AgregarMedidasAsync(FechaMedida, CorreoCliente, BicepIzquierdo, BicepDerecho, Abdomen, CuadricepIzquierdo, CuadricepDerecho, PantorrillaIzquierda, PantorrillaDerecha, null);
        }
        
        /// <remarks/>
        public void AgregarMedidasAsync(System.DateTime FechaMedida, string CorreoCliente, double BicepIzquierdo, double BicepDerecho, double Abdomen, double CuadricepIzquierdo, double CuadricepDerecho, double PantorrillaIzquierda, double PantorrillaDerecha, object userState) {
            if ((this.AgregarMedidasOperationCompleted == null)) {
                this.AgregarMedidasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarMedidasOperationCompleted);
            }
            this.InvokeAsync("AgregarMedidas", new object[] {
                        FechaMedida,
                        CorreoCliente,
                        BicepIzquierdo,
                        BicepDerecho,
                        Abdomen,
                        CuadricepIzquierdo,
                        CuadricepDerecho,
                        PantorrillaIzquierda,
                        PantorrillaDerecha}, this.AgregarMedidasOperationCompleted, userState);
        }
        
        private void OnAgregarMedidasOperationCompleted(object arg) {
            if ((this.AgregarMedidasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarMedidasCompleted(this, new AgregarMedidasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerUltimaMedida", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ObtenerUltimaMedida(string CorreoCliente) {
            object[] results = this.Invoke("ObtenerUltimaMedida", new object[] {
                        CorreoCliente});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerUltimaMedidaAsync(string CorreoCliente) {
            this.ObtenerUltimaMedidaAsync(CorreoCliente, null);
        }
        
        /// <remarks/>
        public void ObtenerUltimaMedidaAsync(string CorreoCliente, object userState) {
            if ((this.ObtenerUltimaMedidaOperationCompleted == null)) {
                this.ObtenerUltimaMedidaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerUltimaMedidaOperationCompleted);
            }
            this.InvokeAsync("ObtenerUltimaMedida", new object[] {
                        CorreoCliente}, this.ObtenerUltimaMedidaOperationCompleted, userState);
        }
        
        private void OnObtenerUltimaMedidaOperationCompleted(object arg) {
            if ((this.ObtenerUltimaMedidaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerUltimaMedidaCompleted(this, new ObtenerUltimaMedidaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerMedida", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ObtenerMedida(string CorreoCliente, System.DateTime FechaDieta) {
            object[] results = this.Invoke("ObtenerMedida", new object[] {
                        CorreoCliente,
                        FechaDieta});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerMedidaAsync(string CorreoCliente, System.DateTime FechaDieta) {
            this.ObtenerMedidaAsync(CorreoCliente, FechaDieta, null);
        }
        
        /// <remarks/>
        public void ObtenerMedidaAsync(string CorreoCliente, System.DateTime FechaDieta, object userState) {
            if ((this.ObtenerMedidaOperationCompleted == null)) {
                this.ObtenerMedidaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerMedidaOperationCompleted);
            }
            this.InvokeAsync("ObtenerMedida", new object[] {
                        CorreoCliente,
                        FechaDieta}, this.ObtenerMedidaOperationCompleted, userState);
        }
        
        private void OnObtenerMedidaOperationCompleted(object arg) {
            if ((this.ObtenerMedidaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerMedidaCompleted(this, new ObtenerMedidaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerMedicionCompleta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ObtenerMedicionCompleta(int CodigoMedida) {
            object[] results = this.Invoke("ObtenerMedicionCompleta", new object[] {
                        CodigoMedida});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerMedicionCompletaAsync(int CodigoMedida) {
            this.ObtenerMedicionCompletaAsync(CodigoMedida, null);
        }
        
        /// <remarks/>
        public void ObtenerMedicionCompletaAsync(int CodigoMedida, object userState) {
            if ((this.ObtenerMedicionCompletaOperationCompleted == null)) {
                this.ObtenerMedicionCompletaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerMedicionCompletaOperationCompleted);
            }
            this.InvokeAsync("ObtenerMedicionCompleta", new object[] {
                        CodigoMedida}, this.ObtenerMedicionCompletaOperationCompleted, userState);
        }
        
        private void OnObtenerMedicionCompletaOperationCompleted(object arg) {
            if ((this.ObtenerMedicionCompletaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerMedicionCompletaCompleted(this, new ObtenerMedicionCompletaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BuscarUsuarioCompletedEventHandler(object sender, BuscarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BuscarUsuarioTodoCompletedEventHandler(object sender, BuscarUsuarioTodoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarUsuarioTodoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarUsuarioTodoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CrearUsuarioCompletedEventHandler(object sender, CrearUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BuscarClienteCompletedEventHandler(object sender, BuscarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BuscarUltimoRegistroCompletedEventHandler(object sender, BuscarUltimoRegistroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarUltimoRegistroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarUltimoRegistroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AgregarDatosClienteCompletedEventHandler(object sender, AgregarDatosClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarDatosClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarDatosClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BuscarUltimoRegistroHarrisCompletedEventHandler(object sender, BuscarUltimoRegistroHarrisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarUltimoRegistroHarrisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarUltimoRegistroHarrisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BuscarRegistroHarrisCompletedEventHandler(object sender, BuscarRegistroHarrisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarRegistroHarrisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarRegistroHarrisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AgregarRegistroHarrisCompletedEventHandler(object sender, AgregarRegistroHarrisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarRegistroHarrisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarRegistroHarrisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AgregarDietaCompletedEventHandler(object sender, AgregarDietaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarDietaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarDietaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ObtenerUltimaDietaCompletedEventHandler(object sender, ObtenerUltimaDietaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerUltimaDietaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerUltimaDietaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ObtenerDietaCompletedEventHandler(object sender, ObtenerDietaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerDietaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerDietaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AgregarRelacionCompletedEventHandler(object sender, AgregarRelacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarRelacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarRelacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ObtenerCatalogoAlimentosCompletedEventHandler(object sender, ObtenerCatalogoAlimentosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerCatalogoAlimentosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerCatalogoAlimentosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ObtenerDietaCompletaCompletedEventHandler(object sender, ObtenerDietaCompletaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerDietaCompletaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerDietaCompletaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AgregarMedidasCompletedEventHandler(object sender, AgregarMedidasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarMedidasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarMedidasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ObtenerUltimaMedidaCompletedEventHandler(object sender, ObtenerUltimaMedidaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerUltimaMedidaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerUltimaMedidaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ObtenerMedidaCompletedEventHandler(object sender, ObtenerMedidaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerMedidaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerMedidaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ObtenerMedicionCompletaCompletedEventHandler(object sender, ObtenerMedicionCompletaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerMedicionCompletaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerMedicionCompletaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591