#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Victus.Resource", IsApplication=true)]

namespace Victus
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int planets_array = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int backgroundcolor = 2130968578;
			
			// aapt resource value: 0x7f04000b
			public const int black_overlay = 2130968587;
			
			// aapt resource value: 0x7f040007
			public const int colorAccent = 2130968583;
			
			// aapt resource value: 0x7f040000
			public const int colorPrimary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int colorPrimaryDark = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int darkblue = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int deeppurple = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int green = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int lightgray = 2130968579;
			
			// aapt resource value: 0x7f04000a
			public const int pink = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int testcolorblue = 2130968585;
			
			// aapt resource value: 0x7f040005
			public const int yello = 2130968581;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int datos = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int generoArray = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07001a
			public const int Registrarme = 2131165210;
			
			// aapt resource value: 0x7f070005
			public const int actividadAlta = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int actividadBaja = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int actividadMedia = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int actividadMuyAlta = 2131165190;
			
			// aapt resource value: 0x7f070002
			public const int actividadMuyBaja = 2131165186;
			
			// aapt resource value: 0x7f070009
			public const int btnCalorias = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int btnDatos = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int btnDietar = 2131165194;
			
			// aapt resource value: 0x7f07001b
			public const int btnIngresar = 2131165211;
			
			// aapt resource value: 0x7f070019
			public const int btnIngresarLogin = 2131165209;
			
			// aapt resource value: 0x7f07000b
			public const int btnMedidas = 2131165195;
			
			// aapt resource value: 0x7f070022
			public const int btnModificarDatos = 2131165218;
			
			// aapt resource value: 0x7f07000e
			public const int btnModificarDieta = 2131165198;
			
			// aapt resource value: 0x7f070013
			public const int btnModificarDietaForm = 2131165203;
			
			// aapt resource value: 0x7f070007
			public const int btnModificarNivelActividadForm = 2131165191;
			
			// aapt resource value: 0x7f07002d
			public const int btnModificarNivelCalorico = 2131165229;
			
			// aapt resource value: 0x7f07001c
			public const int btnRegistrarme = 2131165212;
			
			// aapt resource value: 0x7f070027
			public const int inputAltura = 2131165223;
			
			// aapt resource value: 0x7f070030
			public const int inputCedula = 2131165232;
			
			// aapt resource value: 0x7f070036
			public const int inputClave = 2131165238;
			
			// aapt resource value: 0x7f070018
			public const int inputClaveLogin = 2131165208;
			
			// aapt resource value: 0x7f070033
			public const int inputCorreo = 2131165235;
			
			// aapt resource value: 0x7f070016
			public const int inputCorreoLogin = 2131165206;
			
			// aapt resource value: 0x7f070029
			public const int inputEdad = 2131165225;
			
			// aapt resource value: 0x7f070032
			public const int inputNombre = 2131165234;
			
			// aapt resource value: 0x7f070025
			public const int inputPeso = 2131165221;
			
			// aapt resource value: 0x7f07000d
			public const int listDieta = 2131165197;
			
			// aapt resource value: 0x7f070010
			public const int radioBajarPeso = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int radioMantenerPeso = 2131165201;
			
			// aapt resource value: 0x7f070001
			public const int radioNivelActividad = 2131165185;
			
			// aapt resource value: 0x7f070012
			public const int radioSubirPeso = 2131165202;
			
			// aapt resource value: 0x7f070035
			public const int spinner = 2131165237;
			
			// aapt resource value: 0x7f070020
			public const int txtAgua = 2131165216;
			
			// aapt resource value: 0x7f070026
			public const int txtAltura = 2131165222;
			
			// aapt resource value: 0x7f07002b
			public const int txtCalorias = 2131165227;
			
			// aapt resource value: 0x7f07002f
			public const int txtCedula = 2131165231;
			
			// aapt resource value: 0x7f070017
			public const int txtClave = 2131165207;
			
			// aapt resource value: 0x7f070015
			public const int txtCorreo = 2131165205;
			
			// aapt resource value: 0x7f070023
			public const int txtDatosForm = 2131165219;
			
			// aapt resource value: 0x7f07000c
			public const int txtDieta = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int txtDietaForm = 2131165199;
			
			// aapt resource value: 0x7f070028
			public const int txtEdad = 2131165224;
			
			// aapt resource value: 0x7f070034
			public const int txtGenero = 2131165236;
			
			// aapt resource value: 0x7f07001e
			public const int txtIMC = 2131165214;
			
			// aapt resource value: 0x7f070014
			public const int txtLogin = 2131165204;
			
			// aapt resource value: 0x7f07001d
			public const int txtMisDatos = 2131165213;
			
			// aapt resource value: 0x7f070000
			public const int txtNivelActividad = 2131165184;
			
			// aapt resource value: 0x7f07002a
			public const int txtNivelCalorico = 2131165226;
			
			// aapt resource value: 0x7f070031
			public const int txtNombre = 2131165233;
			
			// aapt resource value: 0x7f070024
			public const int txtPeso = 2131165220;
			
			// aapt resource value: 0x7f07002e
			public const int txtRegistro = 2131165230;
			
			// aapt resource value: 0x7f070021
			public const int userAgua = 2131165217;
			
			// aapt resource value: 0x7f07002c
			public const int userCalorias = 2131165228;
			
			// aapt resource value: 0x7f07001f
			public const int userIMC = 2131165215;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CaloriasForm = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Dashboard = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Dieta = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DietaForm = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Login = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MisDatos = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MisDatosForm = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int NivelCalorico = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Registro = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int planet_prompt = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
